export const questions = [
    {
        id: 1,
        text: "What is the result of 5 multiplied by 7?",
        type: "Math",
        difficulty: "Easy",
        option1: "10",
        option2: "20",
        option3: "25",
        option4: "35",
        option5: "40",
        chapterId: 1,
        answer: "35",
    },
    {
        id: 2,
        text: "Solve for x: 2x - 8 = 16.",
        type: "Algebra",
        difficulty: "Medium",
        option1: "2",
        option2: "4",
        option3: "8",
        option4: "12",
        option5: "16",
        chapterId: 1,
        answer: "16",
    },
    {
        id: 3,
        text: "If a triangle has angles measuring 30 degrees, 60 degrees, and 90 degrees, what type of triangle is it?",
        type: "Geometry",
        difficulty: "Easy",
        option1: "Scalene triangle",
        option2: "Equilateral triangle",
        option3: "Isosceles triangle",
        option4: "Right triangle",
        option5: "Obtuse triangle",
        chapterId: 1,
        answer: "Right triangle",
    }, {
        id: 3,
        text: "If a triangle has angles measuring 30 degrees, 60 degrees, and 90 degrees, what type of triangle is it?",
        type: "Math",
        difficulty: "Easy",
        option1: "Scalene triangle",
        option2: "Equilateral triangle",
        option3: "Isosceles triangle",
        option4: "Right triangle",
        option5: "Obtuse triangle",
        chapterId: 1,
        answer: "Right triangle",
    },
    {
        id: 4,
        text: "What is the value of π (pi) to two decimal places?",
        type: "Math",
        difficulty: "Easy",
        option1: "3.14",
        option2: "3.141",
        option3: "3.142",
        option4: "3.1416",
        option5: "3.14159",
        chapterId: 1,
        answer: "3.14",
    },
    {
        id: 5,
        text: "Solve for x: 2x - 8 = 16.",
        type: "Math",
        difficulty: "Medium",
        option1: "5",
        option2: "6",
        option3: "7",
        option4: "8",
        option5: "9",
        chapterId: 1,
        answer: "12",
    },
    {
        id: 6,
        text: "What is the result of 7 divided by 0?",
        type: "Math",
        difficulty: "Medium",
        option1: "0",
        option2: "1",
        option3: "Infinity",
        option4: "Undefined",
        option5: "7",
        chapterId: 1,
        answer: "Infinity",
    },
    {
        id: 7,
        text: "What is the square root of 81?",
        type: "Math",
        difficulty: "Easy",
        option1: "6",
        option2: "7",
        option3: "8",
        option4: "9",
        option5: "10",
        chapterId: 1,
        answer: "9",
    },
    {
        id: 8,
        text: "If a train travels at a speed of 60 miles per hour, how far will it travel in 3 hours?",
        type: "Math",
        difficulty: "Medium",
        option1: "120 miles",
        option2: "160 miles",
        option3: "180 miles",
        option4: "200 miles",
        option5: "240 miles",
        chapterId: 1,
        answer: "180 miles",
    },
    {
        id: 9,
        text: "What is the sum of 5 and 8?",
        type: "Math",
        difficulty: "Easy",
        option1: "10",
        option2: "11",
        option3: "12",
        option4: "13",
        option5: "14",
        chapterId: 1,
        answer: "13",
    },
    {
        id: 10,
        text: "Solve for x: 3x + 9 = 24.",
        type: "Math",
        difficulty: "Medium",
        option1: "5",
        option2: "6",
        option3: "7",
        option4: "8",
        option5: "9",
        chapterId: 1,
        answer: "5",
    },
    // Add more questions here
];
export const initialQuestion = {
    id: '',
    text: '',
    type: '',
    difficulty: '',
    option1: '',
    option2: '',
    option3: '',
    option4: '',
    option5: '',
    answer: '',
};